### ISSUE TITLE
JPA converter generated for `Association`s does not work on Boot 2.6

### ISSUE THREAD

**Issue by aaryadewa** [xmolecules/jmolecules-integrations#211] opened 2023-12-10 11:11 UTC
I am using Spring Boot 2.6.2 in my project. The `org.hibernate.MappingException` is thrown when I use `Association`  type. I tried this also with the `jmolecules-spring-data-jpa` in `jmolecules-examples`, which is using Spring Boot version 3.6.1 as I write this message. The test is completed successfully. But when I change the Spring Boot version to 2.6.2, it's complaining:
```
javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: No Dialect mapping for JDBC type: 821576394
```
This is the start of the stack trace.
![image](https://github.com/xmolecules/jmolecules/assets/1624931/db7feb3b-4e75-4ae7-a0d1-de49d52617e6)
Does JMolecules support Spring Boot 2.x?

**Comment by odrotbohm** [comment] 2023-12-20 06:49
If you can provide a reproducer project, I can take a look. While we have general integration tests against Spring Boot back until 2.6, note that the latest 2.6 depends on Hibernate 5.6.15.Final. Both that Boot and Hibernate versions have been effectively out of support for quite a while. I can only recommend moving to a newer Spring Boot version, or, at least, upgrade to 2.7.15, which is the version we build against.

**Comment by odrotbohm** [comment] 2024-02-20 10:29
Closing due to lack of feedback and the Boot version this is reported as broken against being severely outdated.

**Closed by odrotbohm** 2024-02-20 10:29 UTC
Labels: resolution: won't-fix
